new ideas branch (my bad LMAO)
ubcbiomod/biomod2023 pull request #13
Opened 2023-07-30 20:02 UTC by rowelsabahat

2023-08-07 22:24 UTC, daniel-panhead requested changes

2023-08-07 22:24 UTC, daniel-panhead commented on src/views/IdeasView.vue
buttons are very sexy, but could you add a transition for the SVG in the idea card to match up with the rest of the card? Right now it instantly changes color on hover which is different from the rest of the card

2023-08-08 00:58 UTC, rowelsabahat commented on src/views/IdeasView.vue
fixed it (maybe)

2023-08-08 18:51 UTC, daniel-panhead commented on src/views/IdeasView.vue
yahoo

2023-08-08 18:51 UTC, daniel-panhead approved these changes
sexy smexy

2023-08-08 18:52 UTC, daniel-panhead commented
Fixed a random merge error of literal whitespace

2023-08-12 00:32 UTC, merged