Responsive Team Page
ubcbiomod/biomod2023 pull request #45
Opened 2023-10-23 22:27 UTC by IcedTea2K

Team page is now responsive to all screen sizes! Things to note:
- On mobile, the card only toggles when the user "touches" the card
- Also on mobile, swiping is very primitive. It doesn't show the next page in the card and there is no returning animation when the page didn't exceed a threshold
- The carousel has be refactored to using grid for more rigid structure (instead of arbitrary padding :P)

https://github.com/biomod2023/biomod2023/assets/62190721/f2c3c237-e889-452d-bafb-a0d3025e8219

https://github.com/biomod2023/biomod2023/assets/62190721/d4fb6291-bc23-4c5d-abd9-7be7f5476dcf

2023-10-23 23:17 UTC, daniel-panhead requested changes
Looks very slick :D there's just some issues with the responsiveness and breakpoints I think:

![image](https://github.com/biomod2023/biomod2023/assets/57362494/2d2820d4-c68a-4d3b-9e11-3735ac431fcd)

Do you think it might be a good idea to show the current selected subteam in the selection title instead of "Choose Team"?

![image](https://github.com/biomod2023/biomod2023/assets/57362494/53146f4b-cbfe-4071-82f0-dce164b3ef69)

Also the transition from desktop to mobile seems a bit inconsistent - the card description trigger changes from hover to toggle depending on whether touch simulation is active, but the swipe mode only appears when the screen reaches a certain width threshold. Is there any way to have touch support also enable the swipe mode? Or maybe we could just have it always enabled?

2023-10-23 23:17 UTC, daniel-panhead commented on NOTEBOOK.md
Let's just rename this to something more general like `CUSTOM_COMPONENTS.md`

2023-10-23 23:17 UTC, daniel-panhead commented on src/views/TeamView.vue
![image](https://github.com/biomod2023/biomod2023/assets/57362494/34faddfc-40fa-4ca4-bdfc-195f16f5b2e3)

Is it possible to have three cards display on xl screens? It looks a bit awkward because it looks like there's space for a third. Maybe reduce the padding x for the gallery?

Also I'm not sure if this applies to you since I assume you're setting width breakpoints based on when the profile cards are about to touch, but if you're ever doing responsive stuff try to use the [Tailwind CSS breakpoints](https://tailwindcss.com/docs/responsive-design) if possible.

2023-10-28 02:54 UTC, IcedTea2K commented on src/views/TeamView.vue
Yeap, I made it resize more dynamically

2023-10-28 02:54 UTC, IcedTea2K commented on NOTEBOOK.md
Displaying sub-team might have to be added to the back-log

2023-10-28 02:55 UTC, IcedTea2K commented on NOTEBOOK.md
As well as the touch simulation. Right now, I'm working on the assumption that if the screen is smaller than a certain threshold, then it's a phone which uses touch support rather than click/hover. To make it better, we might have to add that to the back-log

2023-10-28 02:56 UTC, IcedTea2K commented
I also populated the team page.
<img width="1050" alt="image" src="https://github.com/biomod2023/biomod2023/assets/62190721/9cb48a30-91c1-479f-a5e9-5321b339b20c">

2023-10-28 04:22 UTC, daniel-panhead commented
Everything looks good, only things I would change is on mobile instead of saying "Choose Team" make it display the name of the team you're currently on; also should we add an "All" category since the total list is so short

2023-10-28 04:23 UTC, daniel-panhead requested changes
Also the spacing's a bit wonky for the descriptions:
![image](https://github.com/biomod2023/biomod2023/assets/57362494/6d6b07df-c625-4332-ba7d-a355cd0b80c6)

and I think we should make the card active background a few shades darker, because right now it's a bit hard to make out the white text against the light gold background.

2023-10-28 06:18 UTC, daniel-panhead approved these changes
Wonky spacing is better than the alternative, also fixed the rest of my nitpicks

2023-10-28 06:46 UTC, merged